### ISSUE TITLE
All tall grass and ferns drop normal wheat seeds

### ISSUE THREAD

**Issue by Gamedash43** [ExcessiveAmountsOfZombies/Croptopia#170]
**Version**
Version 1.4.1

**Platform**
Which platform are you using Croptopia on?
Fabric

**Describe the issue**
All ferns and tall grass mined dropped normal wheat seeds.

**To Reproduce**
Mine tall grass or ferns in any biome.

**Screenshots**
![image](https://user-images.githubusercontent.com/78713426/123873686-e204e400-d904-11eb-814c-65bdacc1e620.png)

**Other Mods**
![image](https://user-images.githubusercontent.com/78713426/123873731-f5b04a80-d904-11eb-9768-e5f4a6228c47.png)

**Additional context**

**Comment by ExcessiveAmountsOfZombies** [comment]
What's the issue here? every single tall grass and fern are dropping wheat seeds? Croptopia plants aren't dropping? By default you have to use a hoe to get the Croptopia seeds, thought I see you do have one. Could also update to 1.5.0, I just released it and it makes it so the crops actually generate in the world, reducing the need to break grass
