### ISSUE TITLE
"Chile" Pepper is misspelt (should be Chili)

### ISSUE THREAD

**Issue by Excel619** [ExcessiveAmountsOfZombies/Croptopia#260]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.17.1

### Croptopia version.

1.6.2

### What happened?

Chili pepper and Chili pepper seeds items are incorrectly named "Chile" (as in the country).
Simple fix is to change the lang files, I can make a PR.

**Comment by ExcessiveAmountsOfZombies** [comment]
This is a bit of a weird one and when I originally saw the issue I asked some of my friends how they spelled it, trying to present the question to them in a way that wouldn't taint how it *should* or *might* be spelled. It was split, some said it was spelled Chili and others said Chile. I've grown up with it as Chile is a pepper and a country and Chili is a dish so that's what I'm going to continue with.

Thank you for making an issue though, it made for an interesting discussion in discord.
