### ISSUE TITLE
Tags are non standard

### ISSUE THREAD

**Issue by 1mphuls3** [ExcessiveAmountsOfZombies/Croptopia#323]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.1

### Croptopia version.

1.8.1

### What happened?

Your mods fruit uses tags that are different than most other mods(Pam's mods, Fruit trees, Neapolitan, etc;) yours adds an "s" at the end of the tag, for example: most use forge:fruits/mango, while yours uses forge:fruits/mangos, this can cause incompatibilities with other mods that have recipes using fruits.

**Comment by Ayutac** [comment]
tags are to be used in plural though

**Comment by Peach774** [comment]
> tags are to be used in plural though

its a bit more complicated than that. forge:fruit is an older tag derived from forge:grain. The standard tag as a result is still forge:fruit, forge:vegetable, etc

**Comment by Peach774** [comment]
> tags are to be used in plural though

you are misunderstanding which part should be plural and which shouldnt; The general tag, forge:fruits, is correct, its the subtag that should be singular, so forge:fruits/strawberry is correct, while forge:fruits/strawberries is not. This is widely mixed across the different tags in the mod and is very important to fix in order to make compatibility with other mods work if they only use one tag as reference.
