### ISSUE TITLE
[Suggestion] The ability to change the saturation of food.

### ISSUE THREAD

**Issue by DanteTooMayCry** [ExcessiveAmountsOfZombies/Croptopia#440]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Lots of food products have high saturated rate. This is greatly exaggerated and makes it unprofitable to produce other food to eat. Simple toasts are enough for whole game.

**Comment by deadtoxaris** [comment]
you can edit any food as you want, go to .minecraft (press hold windows key + R and type %appdata%) > when in .minecraft go to mods folder > in mods go in croptopia > copy-paste it to desktop > open it (you can extract it or not, process is the same) > go to assets folder > in assets go to croptopia > then in textures > then you have 2 folders, find your food in  those folders and change it in any software (like photoshop, csp paint/ex, krita, medibang etc.) > after you change it as you like, you can put it back in where you found the file > press ok to replace the file with one you did and voila, you can now edit all the textures in whole minecraft since process is the same.. asking them to change saturation of each and every item is wayy to much process to do as you see just process for one food item.. good luck if you need any more advice or help comment :)

**Comment by sonicolasj** [comment]
> you can edit any food as you want, go to .minecraft (press hold windows key + R and type %appdata%) > when in .minecraft go to mods folder > in mods go in croptopia > copy-paste it to desktop > open it (you can extract it or not, process is the same) > go to assets folder > in assets go to croptopia > then in textures > then you have 2 folders, find your food in those folders and change it in any software (like photoshop, csp paint/ex, krita, medibang etc.) > after you change it as you like, you can put it back in where you found the file > press ok to replace the file with one you did and voila, you can now edit all the textures in whole minecraft since process is the same.. asking them to change saturation of each and every item is wayy to much process to do as you see just process for one food item.. good luck if you need any more advice or help comment :)

I think you're mistaken here, OP is talking about food saturation, aka. how full you are when eating food.

**Comment by DanteTooMayCry** [comment]
Yes. Exactly.
https://minecraft.fandom.com/wiki/Saturation

**Comment by ExcessiveAmountsOfZombies** [comment]
I made this mod on fabric that lets you change the food values https://www.curseforge.com/minecraft/mc-mods/food-rebalanced

**Comment by DanteTooMayCry** [comment]
Nice. But unfortunately I'm playing on forge

**Comment by ExcessiveAmountsOfZombies** [comment]
this'll appear in the future on forge, still a long way out though
