### ISSUE TITLE
Fruit Leafs do not age correctly.

### ISSUE THREAD

**Issue by im-everyman** [ExcessiveAmountsOfZombies/Croptopia#50]
Leafs with fruits on them are permanently on age 0. Bone mealing them seems to work just fine, but after 90 minecraft days there are no naturally genareted fruits. 
I've tried to reverse engineer it and i think it is because of static age function.

**Comment by MechanosG** [comment]
I think my modpack is having the same issue, ever since I updated Croptopia to 1.2.0.  People on our test server are reporting fruit leaves never regrowing their fruit.  We've tested replanting the trees too, just in case it was an issue with pre-existing leaves, but no change.  We're using MC 1.16.5 on Fabric.

**Comment by ExcessiveAmountsOfZombies** [comment]
the fix is now live.
