### ISSUE TITLE
Using the frying pan consumes the frying pan?

### ISSUE THREAD

**Issue by Technically56** [ExcessiveAmountsOfZombies/Croptopia#635]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.21

### Croptopia version.

3.0.9

### What happened?

Using the frying pan seems to consume the frying pan in crafting recipes. (Pack ATM10)

**Comment by djnifos** [comment]
It happens still with only emi and croptopia.  
https://youtu.be/7H_7RYM0Wo8
![image](https://github.com/user-attachments/assets/116d48b0-1aba-404c-9bfb-e5a57e1a05cf)

**Comment by Pultex** [comment]
yes just tried to see if update fix 
came here to say
newest neo forge eat pans

**Comment by HazardEST** [comment]
im on all the mods 10 and my cooking tools get consumed

**Comment by kingstairs** [comment]
Curiously, I am using Croptopia 3.09 on Fabric 1.21.1 (quite a few other mods but I don't think any of them impact crafting other than perhaps REI?).
I made a batch of hamburgers using a crafting table and the frying pan was _not_ consumed. Haven't made/tested the other cooking tools yet. Note that I made the frying pan in 1.21.1 (it wasn't made in 1.20.x and the world upgraded) - I mention that because Mojang made so many changes with items in 1.21.x that "older" items could be misbehaving?

**Comment by DatrixTheHybridShadowWolf** [comment]
It also could be NeoForge and it's update 21.1.72 (or whatever version it is causing said issue) It's possible that what worked on Fabric with it not being consumed is doing the exact opposite on NeoForged so something in the code is not working properly as it did in Fabric when using NeoForge @kingstairs possibly...

I say that because a few mods that I use currently were at one point on Fabric and now also on NeoForged and those mods had one specific issue in them that wasn't there in the fabric version of the mod. (Water Condenser Mod, and Fluid Tanks Mod being the second one).

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed in 4.0.0
