### ISSUE TITLE
Not being able to right click fruit trees to get fruit, without breaking the tree's or leaves.

### ISSUE THREAD

**Issue by SirTwsted** [ExcessiveAmountsOfZombies/Croptopia#640]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.21.1

### Croptopia version.

3.0.9

### What happened?

Why is it that we can not right-click fruit tree fruits right off the tree, without breaking the leaves?
We should be able to farm fruits off tree's without damaging the tree or leaves.
MANY times, I found myself hungry and there are fruit tree's around me as I am exploring, but I can not 
Just right-click on the fruit that's on the tree's and pluck them for nourishment.

Please add this feature or fix it so we can right-click on fruits within tree's.
Thanks.

**Comment by elowanut** [comment]
This is true as a general rule -- right click harvesting is not working at all in the 3.0.9 NeoForge version of Croptopia. You cannot right click harvest any crops or any trees. Obviously this is particularly problematic with the trees, as you have to break the fruiting blocks to harvest them otherwise.

I tested both the latest Forge version (3.0.4), and the latest fabric version (3.0.9), in addition to the latest NeoForge version (3.0.9). All three were tested with JUST a fresh instance, Croptopia, and EpheroLib. Right click harvesting works just fine in Fabric and the last Forge versions. Only the NeoForge version has a problem.

**Comment by gkr0013** [comment]
Temporarily, to resolve the issue, you can install the 'RightClickHarvest' mod (and disable the need for a hoe).

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed in 4.0.0 (being uploaded rn)
