### ISSUE TITLE
Congradulations! Your mod was kicked out from ATM10 modpack!

### ISSUE THREAD

**Issue by YocyCraft** [ExcessiveAmountsOfZombies/Croptopia#653]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.21.1

### Croptopia version.

-1.-1.-1

### What happened?

![Screenshot_20241030_025209_com huawei browser](https://github.com/user-attachments/assets/0487bd47-cd3d-4fb4-b609-a6d04b31e7ec)
2.5 months, no response for issues. That's punishment for your laziness!

### Additional information.

OHHHHHHHHHHH

**Comment by AmouxFang** [comment]
Hopefully nothing irl happened that is making it difficult to fix, not liking this pams mod, its not the same as it was all those years ago. Missing Croptopia

**Comment by DatrixTheHybridShadowWolf** [comment]
3+ months now...Yeah that is awhile. I'd have waited at least 6 months or so until the issue got fixed. To be fair, you are being rude to the mod author though. Another mod I know about took 7 months or so to finish a mod rewrite. That might be what's going on here...hopefully. If all goes well at least.

**Comment by LordCorellon** [comment]
I realize this may not be the right forum but I'd like to start off by saying that I too would have preferred Croptopia be kept rather then brining in PAM's however I can understand why it was removed.

I believe it was a case of having to choose Immersive Engineering or Croptopia as (I presume due to the bug) the two are incompatible as I attempted to run both at the same time only for there to be an issue with Croptopia and KubeJS trying to create recipies with invalid components.

None of those recipes exist in the ATM kubejs files:
[main/ERROR] [KubeJS Server/]: KubeRecipe.java#518: Could not create recipe from json for croptopia:ie_cloche/cloche_chile_pepper[immersiveengineering:cloche]: java.lang.NullPointerException: Cannot invoke "malte0811.dualcodecs.DualMapCodec.mapCodec()" because the return value of "java.util.function.Function.apply(Object)" is null

Anyways hope the above helps to explain the decision (As I see it) and helps the mod author identify the cause

**Comment by ExcessiveAmountsOfZombies** [comment]
thank u for the congradulations fam i fix many issues in 4.0.0
